### PR TITLE
Generated arginfo with types for PHP >= 8.0

### PR DESCRIPTION
**Pull request by pmurzakov**
As per https://externals.io/message/105970

### CODE REVIEW

**Comment by mikhainin** [comment]
@pmurzakov, thank you for the contribution.

Do you mind adding some comments to readme/comments on how it can be used in the future, please? E.g. if we want to add a new function/parameter, what should we do?

**Comment by pmurzakov** [comment]
I'm not sure if it is worth adding it as a documentation directly into this extension as now it is default and preferable way to declare functions, classes, constants etc in all extensions as well as in PHP internally
e.g. 
https://github.com/php/php-src/blob/master/ext/standard/basic_functions.stub.php
https://github.com/krakjoe/apcu/blob/master/php_apc.stub.php

It is achieved using the following script which is pretty straightforward to use IMO
https://github.com/php/php-src/blob/master/build/gen_stub.php

**Comment by mikhainin** [comment]
If it's the default and preferable way, there must be at least a note in the official doc about it :) 
The link wouldn't hurt...

Unfortunately, our extension is now supported by people who aren't aware of PHP internals almost at all, they have no idea about recent recommendations and I expect the situation to get worse. Any help we can provide them would be really valuable

**Comment by pmurzakov** [comment]
To be honest it is not well documented as well as most of the other standard and preferable things in PHP internals :)
The best link which I was able to find is https://stackoverflow.com/questions/66194531/how-to-compile-php-module-in-php8-0-that-used-to-use-tsrmls-cc-in-php7-but-is-d

Basically to change/add functions/arguments you just need to edit the stub file (it uses PHP syntax so most of things should be pretty straightforward) and call https://github.com/php/php-src/blob/master/build/gen_stub.php to update arginfo files

**Comment by pmurzakov** [comment]
Dropped a line into readme

**Pull request merged**
